Controllers/DetailsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Watch_List_Site.Models;

namespace Watch_List_Site.Controllers
{
    public class DetailsController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private IWatchList _watchListRepo;
        public DetailsController(UserManager<IdentityUser> userManager,IWatchList watchList)
        {
            _userManager = userManager;
            _watchListRepo = watchList;
        }
        public IActionResult Index(int id, string name, string desc, string image, bool isSaved)
        {
            SearchEntry searchEntry = null;

            if (isSaved)
            {
                ViewBag.isSaved = true;
                searchEntry = new SearchEntry
                {
                    Id = id,
                    Original_Name = name,
                    Overview = desc,
                    Poster_Path = image
                };
            }
            else { 
                ViewBag.isSaved = false;
                searchEntry = new SearchEntry
                {
                    Id = id,
                    Original_Name = name,
                    Overview = desc,
                    Poster_Path = "http://image.tmdb.org/t/p/w600_and_h900_bestv2" + image
                };
            }


            return View(searchEntry);
        }

        public async Task<IActionResult> AddToWatchList(string name, string desc, string image)
        {

            IdentityUser user = await _userManager.GetUserAsync(User);
            var entry = new WatchList {
                Title = name,
                Desc = desc,
                PosterUrl = image,
                UserId = user.Id
            };

            _watchListRepo.AddItem(entry);
            _watchListRepo.SaveToDb();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult RemoveFromWatchList(int id)
        {
            _watchListRepo.RemoveItem(id);
            _watchListRepo.SaveToDb();

            return RedirectToAction("Index", "Home");
        }

    }
}

Views/Details/Index.cshtml
@model Watch_List_Site.Models.SearchEntry
@{ 

    if (ViewBag.isSaved)
    {
        <h1>True</h1>
    }
    else
    {
        <h1>False</h1>
    }


    <div class="card mb-3" style="max-width:800px;">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="@Model.Poster_Path" class="card-img" />
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">@Model.Original_Name</h5>
                    <p class="card-text">@Model.Overview</p>
                    @if (ViewBag.isSaved)
                    {
                        <a href="@Url.Action("RemoveFromWatchList", "Details", new { id = Model.Id})" class="btn btn-danger">Remove from Watchlist</a>
                    }
                    else
                    {
                        <a href="@Url.Action("AddToWatchList", "Details", new {name = Model.Original_Name, desc = Model.Overview, image = Model.Poster_Path })" class="btn btn-primary">Add to Watchlist</a>
                    }
                </div>
            </div>
        </div>
    </div>
}